# Generated by Django 4.2 on 2024-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.CharField(max_length=255, unique=True)),
                ('is_attend', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='SquareFeetAttendance',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='qr_code',
            new_name='household',
        ),
        migrations.RemoveField(
            model_name='household',
            name='is_attending',
        ),
    ]
