# Generated by Django 4.2 on 2024-02-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_attend_delete_attendance_delete_squarefeetattendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='household',
            new_name='household_id',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='household',
            new_name='household_id',
        ),
    ]
